config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations',
  sessions: 'users/sessions'
}
  resources :users do
    collection do
      patch :bulk_update
      delete :bulk_delete
    end
  end
  resources :users, controller: 'users/registrations', only: [:new, :create]

  resources :users, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # root to: 'users/sessions#new'

  # Defines the root path route ("/")
  # root "pages#home"
  root to: redirect('/users/sign_in')
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         
  validates :name, presence: true
  def active_for_authentication?
    super && status != 'blocked'
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  before_action :configure_sign_up_params, only: [:create]
  before_action :destroy_session, only: [:new]
  
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end
  

  

  def destroy_session
    sign_out(current_user) if user_signed_in?
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  # protected

# If you have extra params to permit, append them to the sanitizer.


  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  # Uncomment the protected keyword and the configure_sign_up_params method
  

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # PUT /resource
  def update
    if params[:user][:password].present?
      super
    else
      resource.update_without_password(user_params)
      bypass_sign_in(resource, scope: resource_name)
      redirect_to root_path, notice: "Account updated successfully."
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        @users = User.order(:id)
    end
    def bulk_delete
        @selected_users = User.where(id: params.fetch(:user_ids, []).compact)

        if @selected_users.empty?
          # Handle case where no users are selected
          redirect_to users_path,notice: "No users selected for deletion."
          
        else
            # puts "555555555555555555555555anything55555555555555555555555"
            # binding.b
            @selected_users.destroy_all
            redirect_to users_path
          
        end
      end 
    def new
      @user = User.new
    end
    def bulk_update
  
        @selected_users=User.where(id:params.fetch(:user_ids,[]).compact)
        #binding.b
        if params[:commit]=="Blocked"
          @selected_users.update_all(status: :blocked)
          redirect_to users_path, notice: "User status updated successfully."
        elsif params[:commit]=="active"
          @selected_users.update_all(status: :active)
          redirect_to users_path, notice: "User status updated successfully."
        else
          redirect_to users_path, notice: "No user selected."
        end
    end
    def user_params
    params.require(:user).permit(:name, :email, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<head>
  <!-- Other head content -->

  <style>
    .checkbox-label {
      cursor: pointer;
    }

    /* Additional CSS styles */
    /* You can add more styles here */
  </style>

</head>


<tr>
<th scope="row"><%= check_box_tag "user_ids[]", user.id, nil, { multiple: true, form: :bulk_actions_form, data: { checkbox_select_all_target: "child", action: "change->checkbox-select-all#toggleParent"} } %>
 <%= check_box_tag "user_ids[]", user.id, nil, { multiple: true, form: :bulk_delete_form, data: { checkbox_select_all_target: "child01", action: "change->checkbox-select-all#toggleParent"} } %></th>
<td><%=user.name%></td>
<td><%=user.email%></td>
<td><%=user.last_sign_in_at%></td>
<td><%=user.status%></td>

</tr>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="text-center">
  <h1>All Users</h1>
</div>


<div class="d-flex justify-content-space-evenly">
  <%= form_with url: bulk_update_users_path, method: :patch, id: :bulk_actions_form do |form| %>
    <%= form.button type: :submit, name: "commit", value: "active", class: "btn btn-success .active", "data-disable-with": "active" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-unlock " viewBox="0 0 16 16">
        <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2M3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1z"/>
      </svg>
      Active
    <% end %>

    <%= form.button type: :submit, name: "commit", value: "Blocked", class: "btn btn-warning block", "data-disable-with": "Block" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-lock" viewBox="0 0 16 16">
        <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2m3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2M5 8h6a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1"/>
      </svg>
      Block
    <% end %>
  <% end %>

  <div class="d-flex flex-column justify-content-between">
    <%= form_with url: bulk_delete_users_path, method: :DELETE, id: :bulk_delete_form do |form| %>
      <%= form.button type: :submit, name: "commit", value: "Delete", class: "btn btn-danger delete", "data-disable-with": "Delete" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
          <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
        </svg>
        Delete
      <% end %>
    <% end %>
  </div>
</div>

</br>
<div data-controller="checkbox-select-all">
<table class="table table-light table-striped table table-hover table table-bordered">
  <thead>
    <tr>
    
    <th scope="col"><%= check_box_tag "select all", nil, nil, { data: { checkbox_select_all_target: "parent", action: "change->checkbox-select-all#toggleChildren"} } %></th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Last Login</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
  
  </tbody>
</table>
</div>